### ISSUE TITLE
tiles.png is missing

### ISSUE THREAD

**Issue by Aivean** [stolencatkarma/CataclysmLD#1]
Trying to run WYSIWYG.py, getting following stacktrace:
```
python3.6 WYSIWYG.py
loading tile table: tiles.png
Traceback (most recent call last):
  File "WYSIWYG.py", line 307, in <module>
    editor = Editor()
  File "WYSIWYG.py", line 32, in __init__
    self.TileManager = TileManager()
  File "/Users/Aivean/Documents/coding/cataclysm-looming-darkness/CataclysmLD/tile.py", line 36, in __init__
    self.TILE_MAP = self.load_tile_table("tiles.png", self.tilemapPx, self.tilemapPy) # list correlating to .png part of the file. relates to tile.fg and tile.bg
  File "/Users/Aivean/Documents/coding/cataclysm-looming-darkness/CataclysmLD/tile.py", line 19, in load_tile_table
    image = pygame.image.load(filename).convert_alpha()
pygame.error: Couldn't open tiles.png
```

Seems that `tiles.png` is expected.

**Comment by stolencatkarma** [comment]
tiles.png along with several others files we will eventually need were added. thanks for the report.
