### ISSUE TITLE
Windows 10 client startup crash

### ISSUE THREAD

**Issue by Melodeiro** [stolencatkarma/CataclysmLD#18]
Server is running, altrough client isn't starting. Python version is 3.7.2

Stdout:
```Loaded gfx folder /gfx/
Loaded gfx folder gfx/inputbox
Loaded gfx folder gfx/background
Loaded gfx folder gfx/scrollbox/vbar/backward
Loaded gfx folder gfx/scrollbox/vbar/forward
Loaded gfx folder gfx/scrollbox/vbar/decoration
Loaded gfx folder gfx/scrollbox/vbar/grip
Loaded gfx folder gfx/scrollbox/frame/decoration
Traceback (most recent call last):
  File "./client.py", line 648, in <module>
    pyglet.app.run()
  File "C:\Python37\lib\site-packages\pyglet\app\__init__.py", line 138, in run
    event_loop.run()
  File "C:\Python37\lib\site-packages\pyglet\app\base.py", line 142, in run
    self._run()
  File "C:\Python37\lib\site-packages\pyglet\app\base.py", line 154, in _run
    timeout = self.idle()
  File "C:\Python37\lib\site-packages\pyglet\app\base.py", line 281, in idle
    window.dispatch_event('on_draw')
  File "C:\Python37\lib\site-packages\pyglet\window\__init__.py", line 1232, in dispatch_event
    if EventDispatcher.dispatch_event(self, *args) != False:
  File "C:\Python37\lib\site-packages\pyglet\event.py", line 360, in dispatch_event
    self._raise_dispatch_exception(event_type, args, handler)
  File "C:\Python37\lib\site-packages\pyglet\event.py", line 357, in dispatch_event
    if handler(*args):
  File "C:\Python37\lib\site-packages\glooey\root.py", line 108, in on_draw
    self.batch.draw()
  File "C:\Python37\lib\site-packages\pyglet\graphics\__init__.py", line 560, in draw
    func()
  File "C:\Python37\lib\site-packages\glooey\drawing\stencil.py", line 84, in unset_state
    glPopAttrib(GL_ENABLE_BIT)
TypeError: this function takes 0 arguments (1 given)```

**Comment by stolencatkarma** [comment]
this is an issue with glooey itself. there was a patch put out but i don't think the update made it to pip.

in that file replace 

glPopAttrib(GL_ENABLE_BIT)

with 

glPopAttrib()

and it will fix it.

**Comment by Melodeiro** [comment]
Okay, thats helped
