### ISSUE TITLE
Character creation bug and crash

### ISSUE THREAD

**Issue by Melodeiro** [stolencatkarma/CataclysmLD#19]
Xubuntu 18.04.2, python 3.7.2
After pressing character creation button, im having empty scroll panes
![image](https://user-images.githubusercontent.com/2702567/54384256-da25c500-46a4-11e9-927f-69a447f5e135.png)
Clicking top buttons doesn't doing anything. After clicking scroll panes, it crashes (probably crash isn't the main problem, main is empty UI)
stdout of crash:
```
Loaded gfx folder /gfx/
Loaded gfx folder gfx/inputbox
Loaded gfx folder gfx/background
Loaded gfx folder gfx/scrollbox/vbar/backward
Loaded gfx folder gfx/scrollbox/vbar/forward
Loaded gfx folder gfx/scrollbox/vbar/decoration
Loaded gfx folder gfx/scrollbox/vbar/grip
Loaded gfx folder gfx/scrollbox/frame/decoration
--next_update in login--
--next_update in login--
--next_update in character_select--
Traceback (most recent call last):
  File "./client.py", line 648, in <module>
    pyglet.app.run()
  File "/usr/local/lib/python3.7/dist-packages/pyglet/app/__init__.py", line 138, in run
    event_loop.run()
  File "/usr/local/lib/python3.7/dist-packages/pyglet/app/base.py", line 142, in run
    self._run()
  File "/usr/local/lib/python3.7/dist-packages/pyglet/app/base.py", line 155, in _run
    platform_event_loop.step(timeout)
  File "/usr/local/lib/python3.7/dist-packages/pyglet/app/xlib.py", line 125, in step
    device.select()
  File "/usr/local/lib/python3.7/dist-packages/pyglet/canvas/xlib.py", line 168, in select
    dispatch(e)
  File "/usr/local/lib/python3.7/dist-packages/pyglet/window/xlib/__init__.py", line 922, in dispatch_platform_event_view
    event_handler(e)
  File "/usr/local/lib/python3.7/dist-packages/pyglet/window/xlib/__init__.py", line 1155, in _event_motionnotify_view
    x, y, dx, dy, buttons, modifiers)
  File "/usr/local/lib/python3.7/dist-packages/pyglet/window/__init__.py", line 1232, in dispatch_event
    if EventDispatcher.dispatch_event(self, *args) != False:
  File "/usr/local/lib/python3.7/dist-packages/pyglet/event.py", line 357, in dispatch_event
    if handler(*args):
  File "/usr/local/lib/python3.7/dist-packages/glooey/widget.py", line 693, in on_mouse_drag
    child.dispatch_event('on_mouse_drag', x, y, dx, dy, buttons, modifiers)
  File "/usr/local/lib/python3.7/dist-packages/pyglet/event.py", line 367, in dispatch_event
    if getattr(self, event_type)(*args):
  File "/usr/local/lib/python3.7/dist-packages/glooey/widget.py", line 693, in on_mouse_drag
    child.dispatch_event('on_mouse_drag', x, y, dx, dy, buttons, modifiers)
  File "/usr/local/lib/python3.7/dist-packages/pyglet/event.py", line 367, in dispatch_event
    if getattr(self, event_type)(*args):
  File "/usr/local/lib/python3.7/dist-packages/glooey/widget.py", line 693, in on_mouse_drag
    child.dispatch_event('on_mouse_drag', x, y, dx, dy, buttons, modifiers)
  File "/usr/local/lib/python3.7/dist-packages/pyglet/event.py", line 367, in dispatch_event
    if getattr(self, event_type)(*args):
  File "/usr/local/lib/python3.7/dist-packages/glooey/widget.py", line 693, in on_mouse_drag
    child.dispatch_event('on_mouse_drag', x, y, dx, dy, buttons, modifiers)
  File "/usr/local/lib/python3.7/dist-packages/pyglet/event.py", line 367, in dispatch_event
    if getattr(self, event_type)(*args):
  File "/usr/local/lib/python3.7/dist-packages/glooey/widget.py", line 693, in on_mouse_drag
    child.dispatch_event('on_mouse_drag', x, y, dx, dy, buttons, modifiers)
  File "/usr/local/lib/python3.7/dist-packages/pyglet/event.py", line 367, in dispatch_event
    if getattr(self, event_type)(*args):
  File "/usr/local/lib/python3.7/dist-packages/glooey/widget.py", line 693, in on_mouse_drag
    child.dispatch_event('on_mouse_drag', x, y, dx, dy, buttons, modifiers)
  File "/usr/local/lib/python3.7/dist-packages/pyglet/event.py", line 367, in dispatch_event
    if getattr(self, event_type)(*args):
  File "/usr/local/lib/python3.7/dist-packages/glooey/widget.py", line 693, in on_mouse_drag
    child.dispatch_event('on_mouse_drag', x, y, dx, dy, buttons, modifiers)
  File "/usr/local/lib/python3.7/dist-packages/pyglet/event.py", line 367, in dispatch_event
    if getattr(self, event_type)(*args):
  File "/usr/local/lib/python3.7/dist-packages/glooey/widget.py", line 693, in on_mouse_drag
    child.dispatch_event('on_mouse_drag', x, y, dx, dy, buttons, modifiers)
  File "/usr/local/lib/python3.7/dist-packages/pyglet/event.py", line 367, in dispatch_event
    if getattr(self, event_type)(*args):
  File "/usr/local/lib/python3.7/dist-packages/glooey/widget.py", line 693, in on_mouse_drag
    child.dispatch_event('on_mouse_drag', x, y, dx, dy, buttons, modifiers)
  File "/usr/local/lib/python3.7/dist-packages/pyglet/event.py", line 367, in dispatch_event
    if getattr(self, event_type)(*args):
  File "/usr/local/lib/python3.7/dist-packages/glooey/scrolling.py", line 130, in on_mouse_drag
    super().on_mouse_drag(x, y, dx, dy, buttons, modifiers)
  File "/usr/local/lib/python3.7/dist-packages/glooey/widget.py", line 693, in on_mouse_drag
    child.dispatch_event('on_mouse_drag', x, y, dx, dy, buttons, modifiers)
  File "/usr/local/lib/python3.7/dist-packages/pyglet/event.py", line 367, in dispatch_event
    if getattr(self, event_type)(*args):
  File "/usr/local/lib/python3.7/dist-packages/glooey/scrolling.py", line 462, in on_mouse_drag
    self.pane.scroll_percent(drag_percent)
  File "/usr/local/lib/python3.7/dist-packages/vecrec/shapes.py", line 71, in decorator
    return function(self, vector)
  File "/usr/local/lib/python3.7/dist-packages/glooey/scrolling.py", line 284, in scroll_percent
    self._require_rects()
  File "/usr/local/lib/python3.7/dist-packages/glooey/scrolling.py", line 418, in _require_rects
    raise UsageError("can't scroll until the scroll pane has a child widget.")
glooey.helpers.UsageError: can't scroll until the scroll pane has a child widget.
```

**Comment by stolencatkarma** [comment]
this is normal. that part isn't done yet. just leave em blank for now.

**Comment by Melodeiro** [comment]
Okay, commit button seems fine after setting name, i was wrong
