### ISSUE TITLE
I cant seem to start the server

### ISSUE THREAD

**Issue by KillAura7170** [stolencatkarma/CataclysmLD#42]
killaura@Unknown:~/CataclysmLD$ python3 server.py
Traceback (most recent call last):
  File "/home/killaura/.local/lib/python3.9/site-packages/sdl2/dll.py", line 362, in <module>
    dll = DLL("SDL2", ["SDL2", "SDL2-2.0", "SDL2-2.0.0"], os.getenv("PYSDL2_DLL_PATH"))
  File "/home/killaura/.local/lib/python3.9/site-packages/sdl2/dll.py", line 253, in __init__
    raise RuntimeError("could not find any library for %s (%s)" %
RuntimeError: could not find any library for SDL2 (PYSDL2_DLL_PATH: unset)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/killaura/CataclysmLD/server.py", line 13, in <module>
    import sdl2
  File "/home/killaura/.local/lib/python3.9/site-packages/sdl2/__init__.py", line 2, in <module>
    from .dll import get_dll_file, _bind
  File "/home/killaura/.local/lib/python3.9/site-packages/sdl2/dll.py", line 364, in <module>
    raise ImportError(exc)
ImportError: could not find any library for SDL2 (PYSDL2_DLL_PATH: unset)
killaura@Unknown:~/CataclysmLD$ python3 server.py
Traceback (most recent call last):
  File "/home/killaura/.local/lib/python3.9/site-packages/sdl2/dll.py", line 362, in <module>
    dll = DLL("SDL2", ["SDL2", "SDL2-2.0", "SDL2-2.0.0"], os.getenv("PYSDL2_DLL_PATH"))
  File "/home/killaura/.local/lib/python3.9/site-packages/sdl2/dll.py", line 253, in __init__
    raise RuntimeError("could not find any library for %s (%s)" %
RuntimeError: could not find any library for SDL2 (PYSDL2_DLL_PATH: unset)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/killaura/CataclysmLD/server.py", line 13, in <module>
    import sdl2
  File "/home/killaura/.local/lib/python3.9/site-packages/sdl2/__init__.py", line 2, in <module>
    from .dll import get_dll_file, _bind
  File "/home/killaura/.local/lib/python3.9/site-packages/sdl2/dll.py", line 364, in <module>
    raise ImportError(exc)
ImportError: could not find any library for SDL2 (PYSDL2_DLL_PATH: unset)

**Comment by stolencatkarma** [comment]
ImportError: could not find any library for SDL2 (PYSDL2_DLL_PATH: unset)

You seem to be running an old release. did you git clone the repo?

**Comment by KillAura7170** [comment]
Yes I git cloned it

**Comment by stolencatkarma** [comment]
ok must be a leftover import, its a terminal app, doesnt use sdl anymore.

**Comment by KillAura7170** [comment]
ok then we can mark this a closed tnx.

**Comment by stolencatkarma** [comment]
Oh man did I screw up bad. I left the server in a completely broken state. server should be working and i've re-enabled the client for people to mess with. no more telnet or MUD clients.
