### ISSUE TITLE
RuntimeError: Gui(id=0278) is only 854x528, but its children are 466x608

### ISSUE THREAD

**Issue by SwagNaut** [stolencatkarma/CataclysmLD#7]
I just downloaded the lastest build. Then I installed all the required packages with pip.
I could start a server just fine, it even says "Started up Cataclysm: Looming Darkness Server".

But when I try to start the client, I get this:

C:\Programme 2\CataclysmLD-master\CataclysmLD-master>python client.py Swag Naut
Loaded gfx folder gfx/background
Loaded gfx folder gfx/scrollbox/vbar/backward
Loaded gfx folder gfx/scrollbox/vbar/forward
Loaded gfx folder gfx/scrollbox/vbar/decoration
Loaded gfx folder gfx/scrollbox/vbar/grip
Loaded gfx folder gfx/scrollbox/frame/decoration
total TILE_TYPES loaded: 8388
total ITEM_TYPES loaded: 922
total RECIPE_TYPES loaded: 4
HEAD_0
TORSO_0
ARM_LEFT
ARM_RIGHT
LEG_LEFT
LEG_RIGHT
FOOT_LEFT
FOOT_RIGHT
HAND_LEFT
HAND_RIGHT
survivor
added localhost:6317
added 162.211.66.247:6317
Traceback (most recent call last):
  File "client.py", line 473, in <module>
    client = Client(args.first_name, args.last_name)
  File "client.py", line 252, in \_\_init__
    self.LoginWindow = LoginWindow()
  File "client.py", line 191, in \_\_init__
    self.gui.add(self.grid)
  File "C:\Users\philb\AppData\Roaming\Python\Python37\site-packages\glooey\containers.py", line 501, in add
    self.add_front(widget)
  File "C:\Users\philb\AppData\Roaming\Python\Python37\site-packages\glooey\containers.py", line 505, in add_front
    self.insert(widget, layer)
  File "C:\Users\philb\AppData\Roaming\Python\Python37\site-packages\glooey\containers.py", line 514, in insert
    self._repack_and_regroup_children()
  File "C:\Users\philb\AppData\Roaming\Python\Python37\site-packages\glooey\helpers.py", line 90, in wrapped_method
    method(self, *args, **kwargs)
  File "C:\Users\philb\AppData\Roaming\Python\Python37\site-packages\glooey\widget.py", line 1475, in _repack_and_regroup_children
    self._repack()
  File "C:\Users\philb\AppData\Roaming\Python\Python37\site-packages\glooey\helpers.py", line 90, in wrapped_method
    method(self, *args, **kwargs)
  File "C:\Users\philb\AppData\Roaming\Python\Python37\site-packages\glooey\root.py", line 92, in _repack
    self.claimed_width, self.claimed_height,
RuntimeError: Gui(id=0278) is only 854x528, but its children are 466x608.

(I copied the whole error just to be sure I got the important bit)

I don't know exactly caused this error, it may be entirely my fault. But maybe it somehow helps.
I can't wait to play this with a couple of friends or even other people online.

**Comment by stolencatkarma** [comment]
It's not in a stable state. I had to push an emergency fix this morning. I've also been switching from pygame to pyglet for the client so in the middle of that rewrite.

Server should be fine though. Client is a work in progress.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by gcopeland** [comment]
Oh ya... I forgot to make a note of this in my pull request. I changed the window size to allow the widget to fix and this resolved the issue.

**Comment by stolencatkarma** [comment]
latest patch fixes this. thanks for the feedback.
